apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    components: {{ .Values.app.components }}
spec:
  replicas: 1
  selector:
    matchLabels:
      components:
        {{ .Values.app.components }}
  containers:
    - name: short-app
      image: {{ .Values.app.image }}:{{ .Values.app.version }}
      ports:
        - containerPort: {{ .Values.app.port }}
